Repository kira134679/plantique-life, pull requests merged in 2025-09, with the labels that each got.

#2 fix(ci): remove redundant step
  .github/workflows/ci.yml
Labels: bug

#7 Chore/split section for collaboration
  pages/index.html
Labels: chore

#10 Feature/add product card component
  assets/scss/components/_product-card.scss
  components/product-card.ejs
Labels: feature

#13 feat: 調整 danger 顏色 / 修改 border 顏色變數
  assets/scss/utils/_bs-variables.scss
Labels: feature

#12 Feature/index page category section
  assets/scss/index.scss
  assets/scss/pages/index/_category.scss
  pages/index.html
Labels: feature

#20 fix: correct reload path of ejs components
  vite.config.js
Labels: bug
